# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogNanovolt.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogNanovolt(object):
    def setupUi(self, DialogNanovolt):
        DialogNanovolt.setObjectName("DialogNanovolt")
        DialogNanovolt.resize(174, 338)
        self.gridLayout = QtWidgets.QGridLayout(DialogNanovolt)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(DialogNanovolt)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 0, 1, 1)
        self.check_analog = QtWidgets.QCheckBox(DialogNanovolt)
        self.check_analog.setChecked(True)
        self.check_analog.setObjectName("check_analog")
        self.gridLayout.addWidget(self.check_analog, 8, 0, 1, 1)
        self.combo_range = QtWidgets.QComboBox(DialogNanovolt)
        self.combo_range.setObjectName("combo_range")
        self.combo_range.addItem("")
        self.combo_range.setItemText(0, "10 mV")
        self.combo_range.addItem("")
        self.combo_range.setItemText(1, "100 mV")
        self.combo_range.addItem("")
        self.combo_range.setItemText(2, "1 V")
        self.combo_range.addItem("")
        self.combo_range.setItemText(3, "10 V")
        self.combo_range.addItem("")
        self.combo_range.setItemText(4, "100 V")
        self.combo_range.addItem("")
        self.combo_range.setItemText(5, "Autoscale")
        self.gridLayout.addWidget(self.combo_range, 3, 0, 1, 1)
        self._label_4 = QtWidgets.QLabel(DialogNanovolt)
        self._label_4.setObjectName("_label_4")
        self.gridLayout.addWidget(self._label_4, 4, 0, 1, 1)
        self._label_3 = QtWidgets.QLabel(DialogNanovolt)
        self._label_3.setObjectName("_label_3")
        self.gridLayout.addWidget(self._label_3, 2, 0, 1, 1)
        self.spin_rate = QtWidgets.QDoubleSpinBox(DialogNanovolt)
        self.spin_rate.setMinimum(0.01)
        self.spin_rate.setMaximum(60.0)
        self.spin_rate.setProperty("value", 5.0)
        self.spin_rate.setObjectName("spin_rate")
        self.gridLayout.addWidget(self.spin_rate, 5, 0, 1, 1)
        self.check_lsync = QtWidgets.QCheckBox(DialogNanovolt)
        self.check_lsync.setChecked(True)
        self.check_lsync.setObjectName("check_lsync")
        self.gridLayout.addWidget(self.check_lsync, 6, 0, 1, 1)
        self._label_2 = QtWidgets.QLabel(DialogNanovolt)
        self._label_2.setObjectName("_label_2")
        self.gridLayout.addWidget(self._label_2, 0, 0, 1, 1)
        self.combo_channel = QtWidgets.QComboBox(DialogNanovolt)
        self.combo_channel.setObjectName("combo_channel")
        self.combo_channel.addItem("")
        self.combo_channel.addItem("")
        self.gridLayout.addWidget(self.combo_channel, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogNanovolt)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 11, 0, 1, 1)
        self.group_digital = QtWidgets.QGroupBox(DialogNanovolt)
        self.group_digital.setCheckable(True)
        self.group_digital.setChecked(False)
        self.group_digital.setObjectName("group_digital")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_digital)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self._label_5 = QtWidgets.QLabel(self.group_digital)
        self._label_5.setObjectName("_label_5")
        self.gridLayout_2.addWidget(self._label_5, 0, 0, 1, 1)
        self._label_6 = QtWidgets.QLabel(self.group_digital)
        self._label_6.setObjectName("_label_6")
        self.gridLayout_2.addWidget(self._label_6, 0, 1, 1, 1)
        self.radio_repeating = QtWidgets.QRadioButton(self.group_digital)
        self.radio_repeating.setObjectName("radio_repeating")
        self.gridLayout_2.addWidget(self.radio_repeating, 2, 0, 1, 1)
        self.spin_filter = QtWidgets.QSpinBox(self.group_digital)
        self.spin_filter.setMinimum(1)
        self.spin_filter.setMaximum(100)
        self.spin_filter.setProperty("value", 10)
        self.spin_filter.setObjectName("spin_filter")
        self.gridLayout_2.addWidget(self.spin_filter, 1, 1, 1, 1)
        self.radio_moving = QtWidgets.QRadioButton(self.group_digital)
        self.radio_moving.setChecked(True)
        self.radio_moving.setObjectName("radio_moving")
        self.gridLayout_2.addWidget(self.radio_moving, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.group_digital, 9, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 110, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 0, 1, 1)

        self.retranslateUi(DialogNanovolt)
        self.buttonBox.accepted.connect(DialogNanovolt.accept)
        self.buttonBox.rejected.connect(DialogNanovolt.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogNanovolt)
        DialogNanovolt.setTabOrder(self.combo_channel, self.combo_range)
        DialogNanovolt.setTabOrder(self.combo_range, self.spin_rate)
        DialogNanovolt.setTabOrder(self.spin_rate, self.check_lsync)
        DialogNanovolt.setTabOrder(self.check_lsync, self.check_analog)
        DialogNanovolt.setTabOrder(self.check_analog, self.radio_moving)
        DialogNanovolt.setTabOrder(self.radio_moving, self.radio_repeating)
        DialogNanovolt.setTabOrder(self.radio_repeating, self.spin_filter)
        DialogNanovolt.setTabOrder(self.spin_filter, self.group_digital)

    def retranslateUi(self, DialogNanovolt):
        _translate = QtCore.QCoreApplication.translate
        DialogNanovolt.setWindowTitle(_translate("DialogNanovolt", "Dialog"))
        self.check_analog.setText(_translate("DialogNanovolt", "Analog filter"))
        self._label_4.setText(_translate("DialogNanovolt", "Rate"))
        self._label_3.setText(_translate("DialogNanovolt", "Range"))
        self.spin_rate.setSuffix(_translate("DialogNanovolt", " PLC"))
        self.check_lsync.setText(_translate("DialogNanovolt", "Line cycle synchronization"))
        self._label_2.setText(_translate("DialogNanovolt", "Input"))
        self.combo_channel.setItemText(0, _translate("DialogNanovolt", "Channel 1"))
        self.combo_channel.setItemText(1, _translate("DialogNanovolt", "Channel 2"))
        self.group_digital.setTitle(_translate("DialogNanovolt", "Digital filter"))
        self._label_5.setText(_translate("DialogNanovolt", "Average"))
        self._label_6.setText(_translate("DialogNanovolt", "Filter count"))
        self.radio_repeating.setText(_translate("DialogNanovolt", "Repeating"))
        self.radio_moving.setText(_translate("DialogNanovolt", "Moving"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogNanovolt = QtWidgets.QDialog()
    ui = Ui_DialogNanovolt()
    ui.setupUi(DialogNanovolt)
    DialogNanovolt.show()
    sys.exit(app.exec_())

