# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WidgetPID.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetPID(object):
    def setupUi(self, WidgetPID):
        WidgetPID.setObjectName("WidgetPID")
        WidgetPID.resize(416, 506)
        self.gridLayout = QtWidgets.QGridLayout(WidgetPID)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(WidgetPID)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ico_status = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ico_status.sizePolicy().hasHeightForWidth())
        self.ico_status.setSizePolicy(sizePolicy)
        self.ico_status.setMinimumSize(QtCore.QSize(32, 32))
        self.ico_status.setObjectName("ico_status")
        self.horizontalLayout_2.addWidget(self.ico_status)
        self.label_status = QtWidgets.QLabel(self.frame)
        self.label_status.setMinimumSize(QtCore.QSize(37, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.horizontalLayout_2.addWidget(self.label_status)
        self.gridLayout.addWidget(self.frame, 11, 2, 1, 1)
        self.spin_kc = QtWidgets.QDoubleSpinBox(WidgetPID)
        self.spin_kc.setDecimals(2)
        self.spin_kc.setMinimum(-1000.0)
        self.spin_kc.setMaximum(1000.0)
        self.spin_kc.setProperty("value", 20.0)
        self.spin_kc.setObjectName("spin_kc")
        self.gridLayout.addWidget(self.spin_kc, 4, 2, 1, 1)
        self.spin_td = QtWidgets.QDoubleSpinBox(WidgetPID)
        self.spin_td.setDecimals(2)
        self.spin_td.setMinimum(-1000.0)
        self.spin_td.setMaximum(1000.0)
        self.spin_td.setProperty("value", 1.0)
        self.spin_td.setObjectName("spin_td")
        self.gridLayout.addWidget(self.spin_td, 8, 2, 1, 1)
        self.line = QtWidgets.QFrame(WidgetPID)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 13, 1)
        self.layout_graph = QtWidgets.QVBoxLayout()
        self.layout_graph.setObjectName("layout_graph")
        self.btn_clear = QtWidgets.QPushButton(WidgetPID)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear.sizePolicy().hasHeightForWidth())
        self.btn_clear.setSizePolicy(sizePolicy)
        self.btn_clear.setObjectName("btn_clear")
        self.layout_graph.addWidget(self.btn_clear)
        self.gridLayout.addLayout(self.layout_graph, 0, 0, 13, 1)
        self.spin_ti = QtWidgets.QDoubleSpinBox(WidgetPID)
        self.spin_ti.setDecimals(2)
        self.spin_ti.setMinimum(-1000.0)
        self.spin_ti.setMaximum(1000.0)
        self.spin_ti.setProperty("value", 5.0)
        self.spin_ti.setObjectName("spin_ti")
        self.gridLayout.addWidget(self.spin_ti, 6, 2, 1, 1)
        self._label_2 = QtWidgets.QLabel(WidgetPID)
        self._label_2.setObjectName("_label_2")
        self.gridLayout.addWidget(self._label_2, 3, 2, 1, 1)
        self.btn_start = QtWidgets.QPushButton(WidgetPID)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(self.btn_start, 12, 2, 1, 1)
        self._label_1 = QtWidgets.QLabel(WidgetPID)
        self._label_1.setObjectName("_label_1")
        self.gridLayout.addWidget(self._label_1, 0, 2, 1, 1)
        self._line = QtWidgets.QFrame(WidgetPID)
        self._line.setFrameShape(QtWidgets.QFrame.HLine)
        self._line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self._line.setObjectName("_line")
        self.gridLayout.addWidget(self._line, 2, 2, 1, 1)
        self._label_3 = QtWidgets.QLabel(WidgetPID)
        self._label_3.setObjectName("_label_3")
        self.gridLayout.addWidget(self._label_3, 5, 2, 1, 1)
        self._label_4 = QtWidgets.QLabel(WidgetPID)
        self._label_4.setObjectName("_label_4")
        self.gridLayout.addWidget(self._label_4, 7, 2, 1, 1)
        self.spin_setpoint = QtWidgets.QDoubleSpinBox(WidgetPID)
        self.spin_setpoint.setMaximum(100.0)
        self.spin_setpoint.setProperty("value", 25.0)
        self.spin_setpoint.setObjectName("spin_setpoint")
        self.gridLayout.addWidget(self.spin_setpoint, 1, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(WidgetPID)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget, 10, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(WidgetPID)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 9, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)

        self.retranslateUi(WidgetPID)
        QtCore.QMetaObject.connectSlotsByName(WidgetPID)

    def retranslateUi(self, WidgetPID):
        _translate = QtCore.QCoreApplication.translate
        WidgetPID.setWindowTitle(_translate("WidgetPID", "Form"))
        self.label_status.setText(_translate("WidgetPID", "Off"))
        self.spin_td.setSuffix(_translate("WidgetPID", " s"))
        self.btn_clear.setText(_translate("WidgetPID", "Clear chart"))
        self.spin_ti.setSuffix(_translate("WidgetPID", " s"))
        self._label_2.setText(_translate("WidgetPID", "Kc"))
        self.btn_start.setText(_translate("WidgetPID", "Start"))
        self._label_1.setText(_translate("WidgetPID", "Setpoint"))
        self._label_3.setText(_translate("WidgetPID", "Ti"))
        self._label_4.setText(_translate("WidgetPID", "Td"))
        self.spin_setpoint.setSuffix(_translate("WidgetPID", " °C"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("WidgetPID", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("WidgetPID", "Value"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetPID = QtWidgets.QWidget()
    ui = Ui_WidgetPID()
    ui.setupUi(WidgetPID)
    WidgetPID.show()
    sys.exit(app.exec_())

