# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WidgetNanoVolt.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetNanoVolt(object):
    def setupUi(self, WidgetNanoVolt):
        WidgetNanoVolt.setObjectName("WidgetNanoVolt")
        WidgetNanoVolt.resize(352, 452)
        self.gridLayout = QtWidgets.QGridLayout(WidgetNanoVolt)
        self.gridLayout.setObjectName("gridLayout")
        self.combo_range = QtWidgets.QComboBox(WidgetNanoVolt)
        self.combo_range.setObjectName("combo_range")
        self.combo_range.addItem("")
        self.combo_range.addItem("")
        self.combo_range.addItem("")
        self.combo_range.addItem("")
        self.combo_range.addItem("")
        self.gridLayout.addWidget(self.combo_range, 4, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(WidgetNanoVolt)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self._label_5 = QtWidgets.QLabel(self.groupBox)
        self._label_5.setObjectName("_label_5")
        self.gridLayout_2.addWidget(self._label_5, 2, 0, 1, 1)
        self._label_6 = QtWidgets.QLabel(self.groupBox)
        self._label_6.setObjectName("_label_6")
        self.gridLayout_2.addWidget(self._label_6, 2, 1, 1, 1)
        self.spin_filter = QtWidgets.QSpinBox(self.groupBox)
        self.spin_filter.setEnabled(False)
        self.spin_filter.setMinimum(1)
        self.spin_filter.setMaximum(100)
        self.spin_filter.setProperty("value", 10)
        self.spin_filter.setObjectName("spin_filter")
        self.gridLayout_2.addWidget(self.spin_filter, 3, 1, 1, 1)
        self.check_digital = QtWidgets.QCheckBox(self.groupBox)
        self.check_digital.setObjectName("check_digital")
        self.gridLayout_2.addWidget(self.check_digital, 0, 0, 1, 1)
        self.radio_repeating = QtWidgets.QRadioButton(self.groupBox)
        self.radio_repeating.setEnabled(False)
        self.radio_repeating.setObjectName("radio_repeating")
        self.gridLayout_2.addWidget(self.radio_repeating, 5, 0, 1, 1)
        self.radio_moving = QtWidgets.QRadioButton(self.groupBox)
        self.radio_moving.setEnabled(False)
        self.radio_moving.setChecked(True)
        self.radio_moving.setObjectName("radio_moving")
        self.gridLayout_2.addWidget(self.radio_moving, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 11, 1, 1, 1)
        self._label_4 = QtWidgets.QLabel(WidgetNanoVolt)
        self._label_4.setObjectName("_label_4")
        self.gridLayout.addWidget(self._label_4, 5, 1, 1, 1)
        self.check_analog = QtWidgets.QCheckBox(WidgetNanoVolt)
        self.check_analog.setChecked(True)
        self.check_analog.setObjectName("check_analog")
        self.gridLayout.addWidget(self.check_analog, 8, 1, 1, 1)
        self.spin_rate = QtWidgets.QDoubleSpinBox(WidgetNanoVolt)
        self.spin_rate.setMinimum(0.01)
        self.spin_rate.setMaximum(60.0)
        self.spin_rate.setProperty("value", 5.0)
        self.spin_rate.setObjectName("spin_rate")
        self.gridLayout.addWidget(self.spin_rate, 6, 1, 1, 1)
        self._label_1 = QtWidgets.QLabel(WidgetNanoVolt)
        self._label_1.setObjectName("_label_1")
        self.gridLayout.addWidget(self._label_1, 0, 0, 1, 1)
        self.combo_channel = QtWidgets.QComboBox(WidgetNanoVolt)
        self.combo_channel.setObjectName("combo_channel")
        self.combo_channel.addItem("")
        self.combo_channel.addItem("")
        self.gridLayout.addWidget(self.combo_channel, 2, 1, 1, 1)
        self.label_port = QtWidgets.QLabel(WidgetNanoVolt)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_port.setPalette(palette)
        self.label_port.setText("")
        self.label_port.setObjectName("label_port")
        self.gridLayout.addWidget(self.label_port, 13, 0, 1, 1)
        self._label_3 = QtWidgets.QLabel(WidgetNanoVolt)
        self._label_3.setObjectName("_label_3")
        self.gridLayout.addWidget(self._label_3, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 1, 1, 1)
        self._label_2 = QtWidgets.QLabel(WidgetNanoVolt)
        self._label_2.setObjectName("_label_2")
        self.gridLayout.addWidget(self._label_2, 1, 1, 1, 1)
        self.list_port = QtWidgets.QListWidget(WidgetNanoVolt)
        self.list_port.setObjectName("list_port")
        self.gridLayout.addWidget(self.list_port, 1, 0, 12, 1)
        self.btn_connect = QtWidgets.QPushButton(WidgetNanoVolt)
        self.btn_connect.setObjectName("btn_connect")
        self.gridLayout.addWidget(self.btn_connect, 13, 1, 1, 1)
        self.line = QtWidgets.QFrame(WidgetNanoVolt)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 7, 1, 1, 1)

        self.retranslateUi(WidgetNanoVolt)
        self.check_digital.toggled['bool'].connect(self.radio_repeating.setEnabled)
        self.check_digital.toggled['bool'].connect(self.radio_moving.setEnabled)
        self.check_digital.toggled['bool'].connect(self.spin_filter.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(WidgetNanoVolt)

    def retranslateUi(self, WidgetNanoVolt):
        _translate = QtCore.QCoreApplication.translate
        WidgetNanoVolt.setWindowTitle(_translate("WidgetNanoVolt", "Form"))
        self.combo_range.setItemText(0, _translate("WidgetNanoVolt", "10 mV"))
        self.combo_range.setItemText(1, _translate("WidgetNanoVolt", "100 mV"))
        self.combo_range.setItemText(2, _translate("WidgetNanoVolt", "1 V"))
        self.combo_range.setItemText(3, _translate("WidgetNanoVolt", "10 V"))
        self.combo_range.setItemText(4, _translate("WidgetNanoVolt", "100 V"))
        self.groupBox.setTitle(_translate("WidgetNanoVolt", "Digital filter"))
        self._label_5.setText(_translate("WidgetNanoVolt", "Average"))
        self._label_6.setText(_translate("WidgetNanoVolt", "Filter count"))
        self.check_digital.setText(_translate("WidgetNanoVolt", "Enable"))
        self.radio_repeating.setText(_translate("WidgetNanoVolt", "Repeating"))
        self.radio_moving.setText(_translate("WidgetNanoVolt", "Moving"))
        self._label_4.setText(_translate("WidgetNanoVolt", "Rate"))
        self.check_analog.setText(_translate("WidgetNanoVolt", "Analog filter"))
        self.spin_rate.setSuffix(_translate("WidgetNanoVolt", " PLC"))
        self._label_1.setText(_translate("WidgetNanoVolt", "Port"))
        self.combo_channel.setItemText(0, _translate("WidgetNanoVolt", "Channel 1"))
        self.combo_channel.setItemText(1, _translate("WidgetNanoVolt", "Channel 2"))
        self._label_3.setText(_translate("WidgetNanoVolt", "Range"))
        self._label_2.setText(_translate("WidgetNanoVolt", "Input"))
        self.btn_connect.setText(_translate("WidgetNanoVolt", "Connect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetNanoVolt = QtWidgets.QWidget()
    ui = Ui_WidgetNanoVolt()
    ui.setupUi(WidgetNanoVolt)
    WidgetNanoVolt.show()
    sys.exit(app.exec_())

